# Setup
title: The Clever Monkey
tagline: 'A life in progress.'
url: 'http://www.clevermonkey.org'
shorturl: clvrmnky.org

# C'est moi
author:
  name: 'John D. Verne'
  url: 'https://about.me/jverne'
  email: JohnDOTVerneATgmailDOTcom

# Config
timezone: America/Toronto
permalink: pretty
kramdown:
  auto_ids: false
excerpt_separator: <!--more-->

# Defaults
defaults:
   -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
   -
    scope:
        path: ""
        type: "pages"
    values:
        layout: "page"
