# Setup
title: The Clever Monkey
tagline: 'a life in progress'
url: 'http://www.clevermonkey.org'
shorturl: clevermonkey.org

# C'est moi
author:
  name: 'John D. Verne'
  url: 'https://about.me/jverne'
  email: 'John.Verne@gmail.com'

# Config
timezone: America/Toronto
permalink: pretty
kramdown:
  auto_ids: false
excerpt_separator: <a name="more"></a>
gems:
   - jekyll-redirect-from
   - jemoji
   - jekyll-sitemap

# Jekyll Defaults
defaults:
   -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
   -
    scope:
        path: ""
        type: "pages"
    values:
        layout: "page"

# Prose.io config
prose:
   metadata:
     _posts:
       - name: "title"
         field:
           element: "text"
           label: "title"
       - name: "date"
         field:
           element: "text"
           label: "Date"
           value: "CURRENT_DATETIME"
